openapi: 3.0.0
info:
  title: Next Swagger API Example
  version: "1.0"
servers:
- url: https://redocly.vercel.app
paths:
  /api/cancel:
    patch:
      description: Cancels an order
      responses:
        "200":
          description: Cancels an order
  /api/create:
    post:
      description: Creates an order
      responses:
        "200":
          description: Creates an order
  /api/order:
    get:
      description: Returns an order
      responses:
        "200":
          description: Returns an order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/order'
  /api/orders:
    get:
      description: Returns all the orders
      responses:
        "200":
          description: Returns all the orders
  /api/update:
    patch:
      description: Updates an order
      responses:
        "200":
          description: Updates an order
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        createdAt:
          type: string
          format: date-time
    order:
      title: Company
      required:
      - id
      - name
      type: object
      properties:
        id:
          title: order.id
          type: string
        name:
          title: order.name
          type: string
        createdAt:
          title: order.createdAt
          type: string
      additionalProperties: false
